# Site settings
title: Brian's Personal Website
email: weichuyang@163.com
description: 魏楚阳的博客
# > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.

# baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username: brianway
permalink: /:year/:month/:day/:title/

#########################################
# for duoshuo.com commenting system, uncomment following line if you do not want to include duoshuo.com. 
duoshuo_shortname: brianway
duoshuo_url: "http://brianway.github.io"
# disqus.com commenting system. please note that it is exclusive with duoshuo.com
#disqus_shortname: lixizhi
#disqus_url: "http://lixizhi.github.io"
#########################################

timezone: '+0800'

# Build settings
markdown: kramdown
highlighter: rouge


# highlight
# highlighter: pygments
# highlighter: rouge
# highlighter: false

#Gems
gems: [jekyll-paginate]

#Pagination
paginate: 10
paginate_path: "page:num"
